#!/usr/bin/env bash

if ! [[ -f ~/.bashrc ]]; then
	echo 'Creating ~/.bashrc file'
	touch ~/.bashrc
fi

echo "" >> ~/.bashrc
echo "# added by the script at $(pwd)/install" >> ~/.bashrc
echo "export UTIL_INSTALL_DIR=\"$(pwd)\"" >> ~/.bashrc
echo 'PATH=$PATH:'"\"$(pwd)\"" >> ~/.bashrc
echo "##### script end ######" >> ~/.bashrc
echo "" >> ~/.bashrc

export UTIL_INSTALL_DIR="$(pwd)"
PATH="$PATH:$(pwd)"

npm install
