#!/usr/bin/env bash

if (($# < 1)); then
	cat <<EOF
usage: observe [list of element dirs]
EOF
fi

files=()

for dir in "${@:1}"; do
	pushd "$dir" >/dev/null

	name="${dir##*/}"
	git ls-files | grep -hvE '(^\.)|(/\.)|(README)' | while read -r line; do
		printf "%50s => %s\n" "$dir/$line" "../elements/bower_components/$name/$line"
	done

	popd >/dev/null
done > paths.txt

node index.js
