#!/usr/bin/env bash

if (($# < 1)); then
	cat <<EOF
usage: observe [list of element dirs]
EOF
fi

files=()

for dir in "${@:1}"; do
	pushd "$dir" >/dev/null

	 while read -r line; do
		files+=("$dir/$line")
	done < <(git ls-files | grep -hvE '(^\.)|(/\.)|(README)')

	popd >/dev/null
done

chokidar "${files[@]}" | { IFS=: read -ra change; echo "${change[1]}"; }
